txt = "VERYXWELLXDONEXFELLOWXHACKERXTHEXSECRETXKEYWORDXISXBMFNRBBBDRIBXXKVFK?SU??JOUW?KWWURNW?VFNFWJKSVEWVLKXLK?JNJVMTMTEVLKUVJFKNKZEUVUVSKKSZKTNKWVKVSU?SOEVWVJKKZKVKVJWWVSVU?VKVJVJOSVVJUWKSKWVJLFJFJNJFLKVLNFKJUSKKVFJK?K?VNKWVWWVUWUSVJKZU?WWKJKTFKSTMVJKVNKWKWVWVSKK?FSSKVFNLFKSWKKWWVWNVWSKXKKTJFV?"
ans =""
for i in txt:
    if i == 'X':
        ans = ans + " "
        continue
    ans = ans + i

print(ans)